// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fnwm5GU2xZ_UEoPGF1z2FHf2dy1arWk',
    appId: '1:527950241960:web:80a6b229ee107f7ece229d',
    messagingSenderId: '527950241960',
    projectId: 'budjetflow',
    authDomain: 'budjetflow.firebaseapp.com',
    storageBucket: 'budjetflow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChcnv_B5ZP4VO_JWgVCfSa-izltl60AUk',
    appId: '1:527950241960:android:627200980776235cce229d',
    messagingSenderId: '527950241960',
    projectId: 'budjetflow',
    storageBucket: 'budjetflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu3QDv15po8WszRiLwLTAq0G0IoevqOmQ',
    appId: '1:527950241960:ios:d9cf669283a8a127ce229d',
    messagingSenderId: '527950241960',
    projectId: 'budjetflow',
    storageBucket: 'budjetflow.firebasestorage.app',
    iosBundleId: 'com.example.budgetflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu3QDv15po8WszRiLwLTAq0G0IoevqOmQ',
    appId: '1:527950241960:ios:d9cf669283a8a127ce229d',
    messagingSenderId: '527950241960',
    projectId: 'budjetflow',
    storageBucket: 'budjetflow.firebasestorage.app',
    iosBundleId: 'com.example.budgetflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3fnwm5GU2xZ_UEoPGF1z2FHf2dy1arWk',
    appId: '1:527950241960:web:2fea38d42e16e6eace229d',
    messagingSenderId: '527950241960',
    projectId: 'budjetflow',
    authDomain: 'budjetflow.firebaseapp.com',
    storageBucket: 'budjetflow.firebasestorage.app',
  );
}
